[20/Dec/2015:14:29:35] ENGINE Listening for SIGHUP.
[20/Dec/2015:14:29:35] ENGINE Listening for SIGTERM.
[20/Dec/2015:14:29:35] ENGINE Listening for SIGUSR1.
[20/Dec/2015:14:29:35] ENGINE Bus STARTING
[20/Dec/2015:14:29:35] ENGINE Started monitor thread '_TimeoutMonitor'.
[20/Dec/2015:14:29:35] ENGINE Serving on http://0.0.0.0:8080
[20/Dec/2015:14:29:35] ENGINE Bus STARTED
[20/Dec/2015:14:30:12] ENGINE Started monitor thread 'Session cleanup'.
[20/Dec/2015:14:32:28] ENGINE Keyboard Interrupt: shutting down bus
[20/Dec/2015:14:32:28] ENGINE Bus STOPPING
[20/Dec/2015:14:32:28] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 8080)) shut down
[20/Dec/2015:14:32:28] ENGINE Stopped thread '_TimeoutMonitor'.
[20/Dec/2015:14:32:28] ENGINE Stopped thread 'Session cleanup'.
[20/Dec/2015:14:32:28] ENGINE Bus STOPPED
[20/Dec/2015:14:32:28] ENGINE Bus EXITING
[20/Dec/2015:14:32:28] ENGINE Bus EXITED
[20/Dec/2015:14:32:28] ENGINE Waiting for child threads to terminate...
[20/Dec/2015:14:32:30] ENGINE Listening for SIGHUP.
[20/Dec/2015:14:32:30] ENGINE Listening for SIGTERM.
[20/Dec/2015:14:32:30] ENGINE Listening for SIGUSR1.
[20/Dec/2015:14:32:30] ENGINE Bus STARTING
[20/Dec/2015:14:32:30] ENGINE Started monitor thread '_TimeoutMonitor'.
[20/Dec/2015:14:32:30] ENGINE Serving on http://0.0.0.0:8080
[20/Dec/2015:14:32:30] ENGINE Bus STARTED
[20/Dec/2015:14:32:35] ENGINE Started monitor thread 'Session cleanup'.
[20/Dec/2015:14:32:43] HTTP 
Request Headers:
  COOKIE: session_id=593c116338a8e495bff7ab824f2533237ee6eabb
  HOST: localhost:8080
  CONNECTION: keep-alive
  Remote-Addr: 127.0.0.1
  ACCEPT: */*
  USER-AGENT: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:43.0) Gecko/20100101 Firefox/43.0
  X-REQUESTED-WITH: XMLHttpRequest
  ACCEPT-LANGUAGE: en-US,en;q=0.5
  Content-Type: text/xml; charset=utf-8
  REFERER: http://localhost:8080/
  ACCEPT-ENCODING: gzip, deflate
[20/Dec/2015:14:32:43] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/jsontools.py", line 63, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/controller/location.py", line 31, in index
    json = self.location.calculate(lat, lng)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/location.py", line 31, in calculate
    nextEvent = calendar.getNextEvent(*userinfo['calendar_url'])
NameError: global name 'userinfo' is not defined
[20/Dec/2015:14:34:35] ENGINE Keyboard Interrupt: shutting down bus
[20/Dec/2015:14:34:35] ENGINE Bus STOPPING
[20/Dec/2015:14:34:35] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 8080)) shut down
[20/Dec/2015:14:34:35] ENGINE Stopped thread 'Session cleanup'.
[20/Dec/2015:14:34:35] ENGINE Stopped thread '_TimeoutMonitor'.
[20/Dec/2015:14:34:35] ENGINE Bus STOPPED
[20/Dec/2015:14:34:35] ENGINE Bus EXITING
[20/Dec/2015:14:34:35] ENGINE Bus EXITED
[20/Dec/2015:14:34:35] ENGINE Waiting for child threads to terminate...
[20/Dec/2015:14:34:36] ENGINE Listening for SIGHUP.
[20/Dec/2015:14:34:36] ENGINE Listening for SIGTERM.
[20/Dec/2015:14:34:36] ENGINE Listening for SIGUSR1.
[20/Dec/2015:14:34:36] ENGINE Bus STARTING
[20/Dec/2015:14:34:36] ENGINE Started monitor thread '_TimeoutMonitor'.
[20/Dec/2015:14:34:37] ENGINE Serving on http://0.0.0.0:8080
[20/Dec/2015:14:34:37] ENGINE Bus STARTED
[20/Dec/2015:14:34:39] ENGINE Started monitor thread 'Session cleanup'.
[20/Dec/2015:14:34:47] HTTP 
Request Headers:
  COOKIE: session_id=173157b5c4677ad222754ecd55df8da365c94524
  HOST: localhost:8080
  CONNECTION: keep-alive
  Remote-Addr: 127.0.0.1
  ACCEPT: */*
  USER-AGENT: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:43.0) Gecko/20100101 Firefox/43.0
  X-REQUESTED-WITH: XMLHttpRequest
  ACCEPT-LANGUAGE: en-US,en;q=0.5
  Content-Type: text/xml; charset=utf-8
  REFERER: http://localhost:8080/
  ACCEPT-ENCODING: gzip, deflate
[20/Dec/2015:14:34:47] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/jsontools.py", line 63, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/controller/location.py", line 33, in index
    json = self.location.calculate(lat, lng, userinfo)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/location.py", line 31, in calculate
    nextEvent = calendar.getNextEvent(*userinfo['calendar_url'])
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 26, in getNextEvent
    cachedEvents = getCalendarEvents(url)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 16, in getCalendarEvents
    calendar = getCalendar(url)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 10, in getCalendar
    request = get(url)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 553, in send
    adapter = self.get_adapter(url=request.url)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 598, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
InvalidSchema: No connection adapters were found for '(u'https://korppi.jyu.fi/calendar/ical/EqY24Na6bQKYaeT',)'
[20/Dec/2015:14:36:20] ENGINE Keyboard Interrupt: shutting down bus
[20/Dec/2015:14:36:20] ENGINE Bus STOPPING
[20/Dec/2015:14:36:20] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 8080)) shut down
[20/Dec/2015:14:36:20] ENGINE Stopped thread 'Session cleanup'.
[20/Dec/2015:14:36:20] ENGINE Stopped thread '_TimeoutMonitor'.
[20/Dec/2015:14:36:20] ENGINE Bus STOPPED
[20/Dec/2015:14:36:20] ENGINE Bus EXITING
[20/Dec/2015:14:36:20] ENGINE Bus EXITED
[20/Dec/2015:14:36:20] ENGINE Waiting for child threads to terminate...
[20/Dec/2015:14:37:11] ENGINE Listening for SIGHUP.
[20/Dec/2015:14:37:11] ENGINE Listening for SIGTERM.
[20/Dec/2015:14:37:11] ENGINE Listening for SIGUSR1.
[20/Dec/2015:14:37:11] ENGINE Bus STARTING
[20/Dec/2015:14:37:11] ENGINE Started monitor thread '_TimeoutMonitor'.
[20/Dec/2015:14:37:11] ENGINE Serving on http://0.0.0.0:8080
[20/Dec/2015:14:37:11] ENGINE Bus STARTED
[20/Dec/2015:14:37:15] ENGINE Started monitor thread 'Session cleanup'.
[20/Dec/2015:14:38:51] ENGINE Keyboard Interrupt: shutting down bus
[20/Dec/2015:14:38:51] ENGINE Bus STOPPING
[20/Dec/2015:14:38:51] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 8080)) shut down
[20/Dec/2015:14:38:51] ENGINE Stopped thread '_TimeoutMonitor'.
[20/Dec/2015:14:38:51] ENGINE Stopped thread 'Session cleanup'.
[20/Dec/2015:14:38:51] ENGINE Bus STOPPED
[20/Dec/2015:14:38:51] ENGINE Bus EXITING
[20/Dec/2015:14:38:51] ENGINE Bus EXITED
[20/Dec/2015:14:38:51] ENGINE Waiting for child threads to terminate...
[20/Dec/2015:14:38:52] ENGINE Listening for SIGHUP.
[20/Dec/2015:14:38:52] ENGINE Listening for SIGTERM.
[20/Dec/2015:14:38:52] ENGINE Listening for SIGUSR1.
[20/Dec/2015:14:38:52] ENGINE Bus STARTING
[20/Dec/2015:14:38:52] ENGINE Started monitor thread '_TimeoutMonitor'.
[20/Dec/2015:14:38:52] ENGINE Serving on http://0.0.0.0:8080
[20/Dec/2015:14:38:52] ENGINE Bus STARTED
[20/Dec/2015:14:38:57] ENGINE Started monitor thread 'Session cleanup'.
[20/Dec/2015:14:39:06] HTTP 
Request Headers:
  COOKIE: session_id=1b3d1dffde43d7548aa0ab541fc9784c3b074806
  HOST: localhost:8080
  CONNECTION: keep-alive
  Remote-Addr: 127.0.0.1
  ACCEPT: */*
  USER-AGENT: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:43.0) Gecko/20100101 Firefox/43.0
  X-REQUESTED-WITH: XMLHttpRequest
  ACCEPT-LANGUAGE: en-US,en;q=0.5
  Content-Type: text/xml; charset=utf-8
  REFERER: http://localhost:8080/
  ACCEPT-ENCODING: gzip, deflate
[20/Dec/2015:14:39:06] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/jsontools.py", line 63, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/controller/location.py", line 35, in index
    logger.debug(traceback.format_exc())
NameError: global name 'logger' is not defined
[20/Dec/2015:14:39:51] ENGINE Keyboard Interrupt: shutting down bus
[20/Dec/2015:14:39:51] ENGINE Bus STOPPING
[20/Dec/2015:14:39:51] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 8080)) shut down
[20/Dec/2015:14:39:51] ENGINE Stopped thread 'Session cleanup'.
[20/Dec/2015:14:39:51] ENGINE Stopped thread '_TimeoutMonitor'.
[20/Dec/2015:14:39:51] ENGINE Bus STOPPED
[20/Dec/2015:14:39:51] ENGINE Bus EXITING
[20/Dec/2015:14:39:51] ENGINE Bus EXITED
[20/Dec/2015:14:39:51] ENGINE Waiting for child threads to terminate...
[20/Dec/2015:14:39:52] ENGINE Listening for SIGHUP.
[20/Dec/2015:14:39:52] ENGINE Listening for SIGTERM.
[20/Dec/2015:14:39:52] ENGINE Listening for SIGUSR1.
[20/Dec/2015:14:39:52] ENGINE Bus STARTING
[20/Dec/2015:14:39:52] ENGINE Started monitor thread '_TimeoutMonitor'.
[20/Dec/2015:14:39:52] ENGINE Serving on http://0.0.0.0:8080
[20/Dec/2015:14:39:52] ENGINE Bus STARTED
[20/Dec/2015:14:40:00] ENGINE Keyboard Interrupt: shutting down bus
[20/Dec/2015:14:40:00] ENGINE Bus STOPPING
[20/Dec/2015:14:40:00] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 8080)) shut down
[20/Dec/2015:14:40:00] ENGINE Stopped thread '_TimeoutMonitor'.
[20/Dec/2015:14:40:00] ENGINE Bus STOPPED
[20/Dec/2015:14:40:00] ENGINE Bus EXITING
[20/Dec/2015:14:40:00] ENGINE Bus EXITED
[20/Dec/2015:14:40:00] ENGINE Waiting for child threads to terminate...
[20/Dec/2015:14:40:09] ENGINE Listening for SIGHUP.
[20/Dec/2015:14:40:09] ENGINE Listening for SIGTERM.
[20/Dec/2015:14:40:09] ENGINE Listening for SIGUSR1.
[20/Dec/2015:14:40:09] ENGINE Bus STARTING
[20/Dec/2015:14:40:09] ENGINE Started monitor thread '_TimeoutMonitor'.
[20/Dec/2015:14:40:09] ENGINE Serving on http://0.0.0.0:8080
[20/Dec/2015:14:40:09] ENGINE Bus STARTED
[20/Dec/2015:15:02:39] ENGINE Started monitor thread 'Session cleanup'.
[20/Dec/2015:15:02:46] HTTP 
Request Headers:
  COOKIE: session_id=5040c602fc878aa277cbe42801e2677de99c5f53
  HOST: localhost:8080
  CONNECTION: keep-alive
  Remote-Addr: 127.0.0.1
  ACCEPT: */*
  USER-AGENT: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:43.0) Gecko/20100101 Firefox/43.0
  X-REQUESTED-WITH: XMLHttpRequest
  ACCEPT-LANGUAGE: en-US,en;q=0.5
  Content-Type: text/xml; charset=utf-8
  REFERER: http://localhost:8080/
  ACCEPT-ENCODING: gzip, deflate
[20/Dec/2015:15:02:46] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/jsontools.py", line 63, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/controller/location.py", line 35, in index
    return {'error': True,
NameError: global name 'logger' is not defined
[20/Dec/2015:15:11:10] ENGINE Keyboard Interrupt: shutting down bus
[20/Dec/2015:15:11:10] ENGINE Bus STOPPING
[20/Dec/2015:15:11:10] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 8080)) shut down
[20/Dec/2015:15:11:10] ENGINE Stopped thread 'Session cleanup'.
[20/Dec/2015:15:11:10] ENGINE Stopped thread '_TimeoutMonitor'.
[20/Dec/2015:15:11:10] ENGINE Bus STOPPED
[20/Dec/2015:15:11:10] ENGINE Bus EXITING
[20/Dec/2015:15:11:10] ENGINE Bus EXITED
[20/Dec/2015:15:11:10] ENGINE Waiting for child threads to terminate...
[20/Dec/2015:15:11:12] ENGINE Listening for SIGHUP.
[20/Dec/2015:15:11:12] ENGINE Listening for SIGTERM.
[20/Dec/2015:15:11:12] ENGINE Listening for SIGUSR1.
[20/Dec/2015:15:11:12] ENGINE Bus STARTING
[20/Dec/2015:15:11:12] ENGINE Started monitor thread '_TimeoutMonitor'.
[20/Dec/2015:15:11:12] ENGINE Serving on http://0.0.0.0:8080
[20/Dec/2015:15:11:12] ENGINE Bus STARTED
[20/Dec/2015:15:11:16] ENGINE Started monitor thread 'Session cleanup'.
[20/Dec/2015:15:11:23]  No connection adapters were found for '(u'https://korppi.jyu.fi/calendar/ical/EqY24Na6bQKYaeT',)'
[20/Dec/2015:15:12:00]  No connection adapters were found for '(u'https://korppi.jyu.fi/calendar/ical/EqY24Na6bQKYaeT',)'
[20/Dec/2015:15:16:09] ENGINE Keyboard Interrupt: shutting down bus
[20/Dec/2015:15:16:09] ENGINE Bus STOPPING
[20/Dec/2015:15:16:09] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 8080)) shut down
[20/Dec/2015:15:16:09] ENGINE Stopped thread '_TimeoutMonitor'.
[20/Dec/2015:15:16:09] ENGINE Stopped thread 'Session cleanup'.
[20/Dec/2015:15:16:09] ENGINE Bus STOPPED
[20/Dec/2015:15:16:09] ENGINE Bus EXITING
[20/Dec/2015:15:16:09] ENGINE Bus EXITED
[20/Dec/2015:15:16:09] ENGINE Waiting for child threads to terminate...
[20/Dec/2015:15:16:10] ENGINE Listening for SIGHUP.
[20/Dec/2015:15:16:10] ENGINE Listening for SIGTERM.
[20/Dec/2015:15:16:10] ENGINE Listening for SIGUSR1.
[20/Dec/2015:15:16:10] ENGINE Bus STARTING
[20/Dec/2015:15:16:10] ENGINE Started monitor thread '_TimeoutMonitor'.
[20/Dec/2015:15:16:10] ENGINE Serving on http://0.0.0.0:8080
[20/Dec/2015:15:16:10] ENGINE Bus STARTED
[20/Dec/2015:15:16:15] ENGINE Started monitor thread 'Session cleanup'.
[20/Dec/2015:15:16:21]  No connection adapters were found for '(u'https://korppi.jyu.fi/calendar/ical/EqY24Na6bQKYaeT',)'
Traceback (most recent call last):
  File "/mnt/DATA/Development/www/matkanaattori/src/application/controller/location.py", line 32, in index
    json = self.location.calculate(lat, lng, userinfo)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/location.py", line 31, in calculate
    nextEvent = calendar.getNextEvent(*userinfo['calendar_url'])
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 26, in getNextEvent
    cachedEvents = getCalendarEvents(url)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 16, in getCalendarEvents
    calendar = getCalendar(url)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 10, in getCalendar
    request = get(url)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 553, in send
    adapter = self.get_adapter(url=request.url)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 598, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
InvalidSchema: No connection adapters were found for '(u'https://korppi.jyu.fi/calendar/ical/EqY24Na6bQKYaeT',)'
[20/Dec/2015:15:40:22]  No connection adapters were found for '(u'https://korppi.jyu.fi/calendar/ical/EqY24Na6bQKYaeT',)'
Traceback (most recent call last):
  File "/mnt/DATA/Development/www/matkanaattori/src/application/controller/location.py", line 32, in index
    json = self.location.calculate(lat, lng, userinfo)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/location.py", line 31, in calculate
    nextEvent = calendar.getNextEvent(*userinfo['calendar_url'])
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 26, in getNextEvent
    cachedEvents = getCalendarEvents(url)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 16, in getCalendarEvents
    calendar = getCalendar(url)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 10, in getCalendar
    request = get(url)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 553, in send
    adapter = self.get_adapter(url=request.url)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 598, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
InvalidSchema: No connection adapters were found for '(u'https://korppi.jyu.fi/calendar/ical/EqY24Na6bQKYaeT',)'
[20/Dec/2015:15:42:31] ENGINE Keyboard Interrupt: shutting down bus
[20/Dec/2015:15:42:31] ENGINE Bus STOPPING
[20/Dec/2015:15:42:31] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 8080)) shut down
[20/Dec/2015:15:42:31] ENGINE Stopped thread '_TimeoutMonitor'.
[20/Dec/2015:15:42:31] ENGINE Stopped thread 'Session cleanup'.
[20/Dec/2015:15:42:31] ENGINE Bus STOPPED
[20/Dec/2015:15:42:31] ENGINE Bus EXITING
[20/Dec/2015:15:42:31] ENGINE Bus EXITED
[20/Dec/2015:15:42:31] ENGINE Waiting for child threads to terminate...
[20/Dec/2015:15:42:32] ENGINE Listening for SIGHUP.
[20/Dec/2015:15:42:32] ENGINE Listening for SIGTERM.
[20/Dec/2015:15:42:32] ENGINE Listening for SIGUSR1.
[20/Dec/2015:15:42:32] ENGINE Bus STARTING
[20/Dec/2015:15:42:32] ENGINE Started monitor thread '_TimeoutMonitor'.
[20/Dec/2015:15:42:32] ENGINE Serving on http://0.0.0.0:8080
[20/Dec/2015:15:42:32] ENGINE Bus STARTED
[20/Dec/2015:15:42:35] ENGINE Started monitor thread 'Session cleanup'.
[20/Dec/2015:15:42:43]  No connection adapters were found for '(u'https://korppi.jyu.fi/calendar/ical/EqY24Na6bQKYaeT',)'
Traceback (most recent call last):
  File "/mnt/DATA/Development/www/matkanaattori/src/application/controller/location.py", line 32, in index
    json = self.location.calculate(lat, lng, userinfo)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/location.py", line 31, in calculate
    nextEvent = calendar.getNextEvent(*userinfo['calendar_url'])
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 26, in getNextEvent
    cachedEvents = getCalendarEvents(url)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 16, in getCalendarEvents
    calendar = getCalendar(url)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 10, in getCalendar
    request = get(url)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 553, in send
    adapter = self.get_adapter(url=request.url)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 598, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
InvalidSchema: No connection adapters were found for '(u'https://korppi.jyu.fi/calendar/ical/EqY24Na6bQKYaeT',)'
[20/Dec/2015:15:44:52] ENGINE Keyboard Interrupt: shutting down bus
[20/Dec/2015:15:44:52] ENGINE Bus STOPPING
[20/Dec/2015:15:44:52] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 8080)) shut down
[20/Dec/2015:15:44:52] ENGINE Stopped thread '_TimeoutMonitor'.
[20/Dec/2015:15:44:52] ENGINE Stopped thread 'Session cleanup'.
[20/Dec/2015:15:44:52] ENGINE Bus STOPPED
[20/Dec/2015:15:44:52] ENGINE Bus EXITING
[20/Dec/2015:15:44:52] ENGINE Bus EXITED
[20/Dec/2015:15:44:52] ENGINE Waiting for child threads to terminate...
[20/Dec/2015:15:44:54] ENGINE Listening for SIGHUP.
[20/Dec/2015:15:44:54] ENGINE Listening for SIGTERM.
[20/Dec/2015:15:44:54] ENGINE Listening for SIGUSR1.
[20/Dec/2015:15:44:54] ENGINE Bus STARTING
[20/Dec/2015:15:44:54] ENGINE Started monitor thread '_TimeoutMonitor'.
[20/Dec/2015:15:44:54] ENGINE Serving on http://0.0.0.0:8080
[20/Dec/2015:15:44:54] ENGINE Bus STARTED
[20/Dec/2015:15:45:00] ENGINE Started monitor thread 'Session cleanup'.
[20/Dec/2015:15:45:07]  No connection adapters were found for '(u'https://korppi.jyu.fi/calendar/ical/EqY24Na6bQKYaeT',)'
Traceback (most recent call last):
  File "/mnt/DATA/Development/www/matkanaattori/src/application/controller/location.py", line 32, in index
    json = self.location.calculate(lat, lng, userinfo)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/location.py", line 31, in calculate
    nextEvent = calendar.getNextEvent(*userinfo['calendar_url'])
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 26, in getNextEvent
    cachedEvents = getCalendarEvents(url)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 16, in getCalendarEvents
    calendar = getCalendar(url)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 10, in getCalendar
    request = get(url)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 553, in send
    adapter = self.get_adapter(url=request.url)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 598, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
InvalidSchema: No connection adapters were found for '(u'https://korppi.jyu.fi/calendar/ical/EqY24Na6bQKYaeT',)'
[20/Dec/2015:15:45:07] HTTP 
Request Headers:
  COOKIE: session_id=3f3354b792049d31f0e6adebf92add534f5b632d
  HOST: localhost:8080
  CONNECTION: keep-alive
  Remote-Addr: 127.0.0.1
  ACCEPT: */*
  USER-AGENT: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:43.0) Gecko/20100101 Firefox/43.0
  X-REQUESTED-WITH: XMLHttpRequest
  ACCEPT-LANGUAGE: en-US,en;q=0.5
  Content-Type: text/xml; charset=utf-8
  REFERER: http://localhost:8080/
  ACCEPT-ENCODING: gzip, deflate
[20/Dec/2015:15:45:07] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/jsontools.py", line 63, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/controller/location.py", line 36, in index
    raise Exception("Location calculation failed.")
Exception: Location calculation failed.
[20/Dec/2015:15:46:17]  No connection adapters were found for '(u'https://korppi.jyu.fi/calendar/ical/EqY24Na6bQKYaeT',)'
Traceback (most recent call last):
  File "/mnt/DATA/Development/www/matkanaattori/src/application/controller/location.py", line 32, in index
    json = self.location.calculate(lat, lng, userinfo)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/location.py", line 31, in calculate
    nextEvent = calendar.getNextEvent(*userinfo['calendar_url'])
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 26, in getNextEvent
    cachedEvents = getCalendarEvents(url)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 16, in getCalendarEvents
    calendar = getCalendar(url)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 10, in getCalendar
    request = get(url)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 553, in send
    adapter = self.get_adapter(url=request.url)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 598, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
InvalidSchema: No connection adapters were found for '(u'https://korppi.jyu.fi/calendar/ical/EqY24Na6bQKYaeT',)'
[20/Dec/2015:15:46:17] HTTP 
Request Headers:
  COOKIE: session_id=3f3354b792049d31f0e6adebf92add534f5b632d
  HOST: localhost:8080
  CONNECTION: keep-alive
  Remote-Addr: 127.0.0.1
  ACCEPT: */*
  USER-AGENT: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:43.0) Gecko/20100101 Firefox/43.0
  X-REQUESTED-WITH: XMLHttpRequest
  ACCEPT-LANGUAGE: en-US,en;q=0.5
  Content-Type: text/xml; charset=utf-8
  REFERER: http://localhost:8080/
  ACCEPT-ENCODING: gzip, deflate
[20/Dec/2015:15:46:17] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/jsontools.py", line 63, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/controller/location.py", line 36, in index
    raise Exception("Location calculation failed.")
Exception: Location calculation failed.
[20/Dec/2015:15:47:22]  No connection adapters were found for '(u'https://korppi.jyu.fi/calendar/ical/EqY24Na6bQKYaeT',)'
Traceback (most recent call last):
  File "/mnt/DATA/Development/www/matkanaattori/src/application/controller/location.py", line 32, in index
    json = self.location.calculate(lat, lng, userinfo)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/location.py", line 31, in calculate
    nextEvent = calendar.getNextEvent(*userinfo['calendar_url'])
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 26, in getNextEvent
    cachedEvents = getCalendarEvents(url)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 16, in getCalendarEvents
    calendar = getCalendar(url)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 10, in getCalendar
    request = get(url)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 553, in send
    adapter = self.get_adapter(url=request.url)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 598, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
InvalidSchema: No connection adapters were found for '(u'https://korppi.jyu.fi/calendar/ical/EqY24Na6bQKYaeT',)'
[20/Dec/2015:15:47:22] HTTP 
Request Headers:
  COOKIE: session_id=3f3354b792049d31f0e6adebf92add534f5b632d
  HOST: localhost:8080
  CONNECTION: keep-alive
  Remote-Addr: 127.0.0.1
  ACCEPT: */*
  USER-AGENT: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:43.0) Gecko/20100101 Firefox/43.0
  X-REQUESTED-WITH: XMLHttpRequest
  ACCEPT-LANGUAGE: en-US,en;q=0.5
  Content-Type: text/xml; charset=utf-8
  REFERER: http://localhost:8080/
  ACCEPT-ENCODING: gzip, deflate
[20/Dec/2015:15:47:22] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/jsontools.py", line 63, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/controller/location.py", line 36, in index
    raise Exception("Location calculation failed.")
Exception: Location calculation failed.
[20/Dec/2015:15:48:14]  No connection adapters were found for '(u'https://korppi.jyu.fi/calendar/ical/EqY24Na6bQKYaeT',)'
Traceback (most recent call last):
  File "/mnt/DATA/Development/www/matkanaattori/src/application/controller/location.py", line 32, in index
    json = self.location.calculate(lat, lng, userinfo)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/location.py", line 31, in calculate
    nextEvent = calendar.getNextEvent(*userinfo['calendar_url'])
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 26, in getNextEvent
    cachedEvents = getCalendarEvents(url)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 16, in getCalendarEvents
    calendar = getCalendar(url)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 10, in getCalendar
    request = get(url)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 553, in send
    adapter = self.get_adapter(url=request.url)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 598, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
InvalidSchema: No connection adapters were found for '(u'https://korppi.jyu.fi/calendar/ical/EqY24Na6bQKYaeT',)'
[20/Dec/2015:15:48:14] HTTP 
Request Headers:
  COOKIE: session_id=3f3354b792049d31f0e6adebf92add534f5b632d
  HOST: localhost:8080
  CONNECTION: keep-alive
  Remote-Addr: 127.0.0.1
  ACCEPT: */*
  USER-AGENT: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:43.0) Gecko/20100101 Firefox/43.0
  X-REQUESTED-WITH: XMLHttpRequest
  ACCEPT-LANGUAGE: en-US,en;q=0.5
  Content-Type: text/xml; charset=utf-8
  REFERER: http://localhost:8080/
  ACCEPT-ENCODING: gzip, deflate
[20/Dec/2015:15:48:14] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/jsontools.py", line 63, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/controller/location.py", line 36, in index
    raise Exception("Location calculation failed.")
Exception: Location calculation failed.
[20/Dec/2015:15:48:37]  No connection adapters were found for '(u'https://korppi.jyu.fi/calendar/ical/EqY24Na6bQKYaeT',)'
Traceback (most recent call last):
  File "/mnt/DATA/Development/www/matkanaattori/src/application/controller/location.py", line 32, in index
    json = self.location.calculate(lat, lng, userinfo)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/location.py", line 31, in calculate
    nextEvent = calendar.getNextEvent(*userinfo['calendar_url'])
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 26, in getNextEvent
    cachedEvents = getCalendarEvents(url)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 16, in getCalendarEvents
    calendar = getCalendar(url)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 10, in getCalendar
    request = get(url)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 553, in send
    adapter = self.get_adapter(url=request.url)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 598, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
InvalidSchema: No connection adapters were found for '(u'https://korppi.jyu.fi/calendar/ical/EqY24Na6bQKYaeT',)'
[20/Dec/2015:15:48:37] HTTP 
Request Headers:
  COOKIE: session_id=3f3354b792049d31f0e6adebf92add534f5b632d
  HOST: localhost:8080
  CONNECTION: keep-alive
  Remote-Addr: 127.0.0.1
  ACCEPT: */*
  USER-AGENT: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:43.0) Gecko/20100101 Firefox/43.0
  X-REQUESTED-WITH: XMLHttpRequest
  ACCEPT-LANGUAGE: en-US,en;q=0.5
  Content-Type: text/xml; charset=utf-8
  REFERER: http://localhost:8080/
  ACCEPT-ENCODING: gzip, deflate
[20/Dec/2015:15:48:37] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/jsontools.py", line 63, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/controller/location.py", line 36, in index
    raise Exception("Location calculation failed.")
Exception: Location calculation failed.
[20/Dec/2015:15:49:31]  No connection adapters were found for '(u'https://korppi.jyu.fi/calendar/ical/EqY24Na6bQKYaeT',)'
Traceback (most recent call last):
  File "/mnt/DATA/Development/www/matkanaattori/src/application/controller/location.py", line 32, in index
    json = self.location.calculate(lat, lng, userinfo)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/location.py", line 31, in calculate
    nextEvent = calendar.getNextEvent(*userinfo['calendar_url'])
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 26, in getNextEvent
    cachedEvents = getCalendarEvents(url)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 16, in getCalendarEvents
    calendar = getCalendar(url)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 10, in getCalendar
    request = get(url)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 553, in send
    adapter = self.get_adapter(url=request.url)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 598, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
InvalidSchema: No connection adapters were found for '(u'https://korppi.jyu.fi/calendar/ical/EqY24Na6bQKYaeT',)'
[20/Dec/2015:15:49:31] HTTP 
Request Headers:
  COOKIE: session_id=3f3354b792049d31f0e6adebf92add534f5b632d
  HOST: localhost:8080
  CONNECTION: keep-alive
  Remote-Addr: 127.0.0.1
  ACCEPT: */*
  USER-AGENT: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:43.0) Gecko/20100101 Firefox/43.0
  X-REQUESTED-WITH: XMLHttpRequest
  ACCEPT-LANGUAGE: en-US,en;q=0.5
  Content-Type: text/xml; charset=utf-8
  REFERER: http://localhost:8080/
  ACCEPT-ENCODING: gzip, deflate
[20/Dec/2015:15:49:31] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/jsontools.py", line 63, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/controller/location.py", line 36, in index
    raise Exception("Location calculation failed.")
Exception: Location calculation failed.
[20/Dec/2015:15:50:03]  No connection adapters were found for '(u'https://korppi.jyu.fi/calendar/ical/EqY24Na6bQKYaeT',)'
Traceback (most recent call last):
  File "/mnt/DATA/Development/www/matkanaattori/src/application/controller/location.py", line 32, in index
    json = self.location.calculate(lat, lng, userinfo)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/location.py", line 31, in calculate
    nextEvent = calendar.getNextEvent(*userinfo['calendar_url'])
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 26, in getNextEvent
    cachedEvents = getCalendarEvents(url)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 16, in getCalendarEvents
    calendar = getCalendar(url)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 10, in getCalendar
    request = get(url)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 553, in send
    adapter = self.get_adapter(url=request.url)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 598, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
InvalidSchema: No connection adapters were found for '(u'https://korppi.jyu.fi/calendar/ical/EqY24Na6bQKYaeT',)'
[20/Dec/2015:15:50:03] HTTP 
Request Headers:
  COOKIE: session_id=3f3354b792049d31f0e6adebf92add534f5b632d
  HOST: localhost:8080
  CONNECTION: keep-alive
  Remote-Addr: 127.0.0.1
  ACCEPT: */*
  USER-AGENT: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:43.0) Gecko/20100101 Firefox/43.0
  X-REQUESTED-WITH: XMLHttpRequest
  ACCEPT-LANGUAGE: en-US,en;q=0.5
  Content-Type: text/xml; charset=utf-8
  REFERER: http://localhost:8080/
  ACCEPT-ENCODING: gzip, deflate
[20/Dec/2015:15:50:03] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/jsontools.py", line 63, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/controller/location.py", line 36, in index
    raise Exception("Location calculation failed.")
Exception: Location calculation failed.
[20/Dec/2015:15:50:35]  No connection adapters were found for '(u'https://korppi.jyu.fi/calendar/ical/EqY24Na6bQKYaeT',)'
Traceback (most recent call last):
  File "/mnt/DATA/Development/www/matkanaattori/src/application/controller/location.py", line 32, in index
    json = self.location.calculate(lat, lng, userinfo)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/location.py", line 31, in calculate
    nextEvent = calendar.getNextEvent(*userinfo['calendar_url'])
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 26, in getNextEvent
    cachedEvents = getCalendarEvents(url)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 16, in getCalendarEvents
    calendar = getCalendar(url)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 10, in getCalendar
    request = get(url)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 553, in send
    adapter = self.get_adapter(url=request.url)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 598, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
InvalidSchema: No connection adapters were found for '(u'https://korppi.jyu.fi/calendar/ical/EqY24Na6bQKYaeT',)'
[20/Dec/2015:15:50:35] HTTP 
Request Headers:
  COOKIE: session_id=3f3354b792049d31f0e6adebf92add534f5b632d
  HOST: localhost:8080
  CONNECTION: keep-alive
  Remote-Addr: 127.0.0.1
  ACCEPT: */*
  USER-AGENT: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:43.0) Gecko/20100101 Firefox/43.0
  X-REQUESTED-WITH: XMLHttpRequest
  ACCEPT-LANGUAGE: en-US,en;q=0.5
  Content-Type: text/xml; charset=utf-8
  REFERER: http://localhost:8080/
  ACCEPT-ENCODING: gzip, deflate
[20/Dec/2015:15:50:35] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/jsontools.py", line 63, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/controller/location.py", line 36, in index
    raise Exception("Location calculation failed.")
Exception: Location calculation failed.
[20/Dec/2015:15:54:36]  No connection adapters were found for '(u'https://korppi.jyu.fi/calendar/ical/EqY24Na6bQKYaeT',)'
Traceback (most recent call last):
  File "/mnt/DATA/Development/www/matkanaattori/src/application/controller/location.py", line 32, in index
    json = self.location.calculate(lat, lng, userinfo)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/location.py", line 31, in calculate
    nextEvent = calendar.getNextEvent(*userinfo['calendar_url'])
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 26, in getNextEvent
    cachedEvents = getCalendarEvents(url)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 16, in getCalendarEvents
    calendar = getCalendar(url)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 10, in getCalendar
    request = get(url)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 553, in send
    adapter = self.get_adapter(url=request.url)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 598, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
InvalidSchema: No connection adapters were found for '(u'https://korppi.jyu.fi/calendar/ical/EqY24Na6bQKYaeT',)'
[20/Dec/2015:15:54:36] HTTP 
Request Headers:
  COOKIE: session_id=3f3354b792049d31f0e6adebf92add534f5b632d
  HOST: localhost:8080
  CONNECTION: keep-alive
  Remote-Addr: 127.0.0.1
  ACCEPT: */*
  USER-AGENT: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:43.0) Gecko/20100101 Firefox/43.0
  X-REQUESTED-WITH: XMLHttpRequest
  ACCEPT-LANGUAGE: en-US,en;q=0.5
  Content-Type: text/xml; charset=utf-8
  REFERER: http://localhost:8080/
  ACCEPT-ENCODING: gzip, deflate
[20/Dec/2015:15:54:36] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/jsontools.py", line 63, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/controller/location.py", line 36, in index
    raise Exception("Location calculation failed.")
Exception: Location calculation failed.
[20/Dec/2015:15:55:13]  No connection adapters were found for '(u'https://korppi.jyu.fi/calendar/ical/EqY24Na6bQKYaeT',)'
Traceback (most recent call last):
  File "/mnt/DATA/Development/www/matkanaattori/src/application/controller/location.py", line 32, in index
    json = self.location.calculate(lat, lng, userinfo)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/location.py", line 31, in calculate
    nextEvent = calendar.getNextEvent(*userinfo['calendar_url'])
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 26, in getNextEvent
    cachedEvents = getCalendarEvents(url)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 16, in getCalendarEvents
    calendar = getCalendar(url)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 10, in getCalendar
    request = get(url)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 553, in send
    adapter = self.get_adapter(url=request.url)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 598, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
InvalidSchema: No connection adapters were found for '(u'https://korppi.jyu.fi/calendar/ical/EqY24Na6bQKYaeT',)'
[20/Dec/2015:15:55:13] HTTP 
Request Headers:
  COOKIE: session_id=3f3354b792049d31f0e6adebf92add534f5b632d
  HOST: localhost:8080
  CONNECTION: keep-alive
  Remote-Addr: 127.0.0.1
  ACCEPT: */*
  USER-AGENT: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:43.0) Gecko/20100101 Firefox/43.0
  X-REQUESTED-WITH: XMLHttpRequest
  ACCEPT-LANGUAGE: en-US,en;q=0.5
  Content-Type: text/xml; charset=utf-8
  REFERER: http://localhost:8080/
  ACCEPT-ENCODING: gzip, deflate
[20/Dec/2015:15:55:13] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/jsontools.py", line 63, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/controller/location.py", line 36, in index
    raise Exception("Location calculation failed.")
Exception: Location calculation failed.
[20/Dec/2015:16:02:02]  No connection adapters were found for '(u'https://korppi.jyu.fi/calendar/ical/EqY24Na6bQKYaeT',)'
Traceback (most recent call last):
  File "/mnt/DATA/Development/www/matkanaattori/src/application/controller/location.py", line 32, in index
    json = self.location.calculate(lat, lng, userinfo)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/location.py", line 31, in calculate
    nextEvent = calendar.getNextEvent(*userinfo['calendar_url'])
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 26, in getNextEvent
    cachedEvents = getCalendarEvents(url)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 16, in getCalendarEvents
    calendar = getCalendar(url)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 10, in getCalendar
    request = get(url)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 553, in send
    adapter = self.get_adapter(url=request.url)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 598, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
InvalidSchema: No connection adapters were found for '(u'https://korppi.jyu.fi/calendar/ical/EqY24Na6bQKYaeT',)'
[20/Dec/2015:16:02:02] HTTP 
Request Headers:
  COOKIE: session_id=3f3354b792049d31f0e6adebf92add534f5b632d
  HOST: localhost:8080
  CONNECTION: keep-alive
  Remote-Addr: 127.0.0.1
  ACCEPT: */*
  USER-AGENT: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:43.0) Gecko/20100101 Firefox/43.0
  X-REQUESTED-WITH: XMLHttpRequest
  ACCEPT-LANGUAGE: en-US,en;q=0.5
  Content-Type: text/xml; charset=utf-8
  REFERER: http://localhost:8080/
  ACCEPT-ENCODING: gzip, deflate
[20/Dec/2015:16:02:02] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/jsontools.py", line 63, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/controller/location.py", line 36, in index
    raise Exception("Location calculation failed.")
Exception: Location calculation failed.
[20/Dec/2015:16:05:26] ENGINE Keyboard Interrupt: shutting down bus
[20/Dec/2015:16:05:26] ENGINE Bus STOPPING
[20/Dec/2015:16:05:26] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 8080)) shut down
[20/Dec/2015:16:05:26] ENGINE Stopped thread '_TimeoutMonitor'.
[20/Dec/2015:16:05:26] ENGINE Stopped thread 'Session cleanup'.
[20/Dec/2015:16:05:26] ENGINE Bus STOPPED
[20/Dec/2015:16:05:26] ENGINE Bus EXITING
[20/Dec/2015:16:05:26] ENGINE Bus EXITED
[20/Dec/2015:16:05:26] ENGINE Waiting for child threads to terminate...
[20/Dec/2015:16:05:28] ENGINE Listening for SIGHUP.
[20/Dec/2015:16:05:28] ENGINE Listening for SIGTERM.
[20/Dec/2015:16:05:28] ENGINE Listening for SIGUSR1.
[20/Dec/2015:16:05:28] ENGINE Bus STARTING
[20/Dec/2015:16:05:28] ENGINE Started monitor thread '_TimeoutMonitor'.
[20/Dec/2015:16:05:28] ENGINE Serving on http://0.0.0.0:8080
[20/Dec/2015:16:05:28] ENGINE Bus STARTED
[20/Dec/2015:16:05:32] ENGINE Started monitor thread 'Session cleanup'.
[20/Dec/2015:16:05:40]  No connection adapters were found for '(u'https://korppi.jyu.fi/calendar/ical/EqY24Na6bQKYaeT',)'
Traceback (most recent call last):
  File "/mnt/DATA/Development/www/matkanaattori/src/application/controller/location.py", line 32, in index
    json = self.location.calculate(lat, lng, userinfo)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/location.py", line 31, in calculate
    nextEvent = calendar.getNextEvent(*userinfo['calendar_url'])
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 26, in getNextEvent
    cachedEvents = getCalendarEvents(url)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 16, in getCalendarEvents
    calendar = getCalendar(url)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 10, in getCalendar
    request = get(url)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 553, in send
    adapter = self.get_adapter(url=request.url)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 598, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
InvalidSchema: No connection adapters were found for '(u'https://korppi.jyu.fi/calendar/ical/EqY24Na6bQKYaeT',)'
[20/Dec/2015:16:05:40] HTTP 
Request Headers:
  COOKIE: session_id=6b009a9058930625c1aff381c7bb004acc5c7348
  HOST: localhost:8080
  CONNECTION: keep-alive
  Remote-Addr: 127.0.0.1
  ACCEPT: */*
  USER-AGENT: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:43.0) Gecko/20100101 Firefox/43.0
  X-REQUESTED-WITH: XMLHttpRequest
  ACCEPT-LANGUAGE: en-US,en;q=0.5
  Content-Type: text/xml; charset=utf-8
  REFERER: http://localhost:8080/
  ACCEPT-ENCODING: gzip, deflate
[20/Dec/2015:16:05:40] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/jsontools.py", line 63, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/controller/location.py", line 36, in index
    raise Exception("Location calculation failed.")
Exception: Location calculation failed.
[20/Dec/2015:16:06:29] ENGINE Keyboard Interrupt: shutting down bus
[20/Dec/2015:16:06:29] ENGINE Bus STOPPING
[20/Dec/2015:16:06:29] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 8080)) shut down
[20/Dec/2015:16:06:29] ENGINE Stopped thread 'Session cleanup'.
[20/Dec/2015:16:06:29] ENGINE Stopped thread '_TimeoutMonitor'.
[20/Dec/2015:16:06:29] ENGINE Bus STOPPED
[20/Dec/2015:16:06:29] ENGINE Bus EXITING
[20/Dec/2015:16:06:29] ENGINE Bus EXITED
[20/Dec/2015:16:06:29] ENGINE Waiting for child threads to terminate...
[20/Dec/2015:16:06:31] ENGINE Listening for SIGHUP.
[20/Dec/2015:16:06:31] ENGINE Listening for SIGTERM.
[20/Dec/2015:16:06:31] ENGINE Listening for SIGUSR1.
[20/Dec/2015:16:06:31] ENGINE Bus STARTING
[20/Dec/2015:16:06:31] ENGINE Started monitor thread '_TimeoutMonitor'.
[20/Dec/2015:16:06:31] ENGINE Serving on http://0.0.0.0:8080
[20/Dec/2015:16:06:31] ENGINE Bus STARTED
[20/Dec/2015:16:06:34] ENGINE Started monitor thread 'Session cleanup'.
[20/Dec/2015:16:06:41]  No connection adapters were found for '(u'https://korppi.jyu.fi/calendar/ical/EqY24Na6bQKYaeT',)'
Traceback (most recent call last):
  File "/mnt/DATA/Development/www/matkanaattori/src/application/controller/location.py", line 32, in index
    json = self.location.calculate(lat, lng, userinfo)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/location.py", line 31, in calculate
    nextEvent = calendar.getNextEvent(*userinfo['calendar_url'])
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 26, in getNextEvent
    cachedEvents = getCalendarEvents(url)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 16, in getCalendarEvents
    calendar = getCalendar(url)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 10, in getCalendar
    request = get(url)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 553, in send
    adapter = self.get_adapter(url=request.url)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 598, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
InvalidSchema: No connection adapters were found for '(u'https://korppi.jyu.fi/calendar/ical/EqY24Na6bQKYaeT',)'
[20/Dec/2015:16:12:08] ENGINE Keyboard Interrupt: shutting down bus
[20/Dec/2015:16:12:08] ENGINE Bus STOPPING
[20/Dec/2015:16:12:08] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 8080)) shut down
[20/Dec/2015:16:12:08] ENGINE Stopped thread '_TimeoutMonitor'.
[20/Dec/2015:16:12:08] ENGINE Stopped thread 'Session cleanup'.
[20/Dec/2015:16:12:08] ENGINE Bus STOPPED
[20/Dec/2015:16:12:08] ENGINE Bus EXITING
[20/Dec/2015:16:12:08] ENGINE Bus EXITED
[20/Dec/2015:16:12:08] ENGINE Waiting for child threads to terminate...
[20/Dec/2015:16:12:09] ENGINE Listening for SIGHUP.
[20/Dec/2015:16:12:09] ENGINE Listening for SIGTERM.
[20/Dec/2015:16:12:09] ENGINE Listening for SIGUSR1.
[20/Dec/2015:16:12:09] ENGINE Bus STARTING
[20/Dec/2015:16:12:09] ENGINE Started monitor thread '_TimeoutMonitor'.
[20/Dec/2015:16:12:09] ENGINE Serving on http://0.0.0.0:8080
[20/Dec/2015:16:12:09] ENGINE Bus STARTED
[20/Dec/2015:16:12:13] ENGINE Started monitor thread 'Session cleanup'.
[20/Dec/2015:16:12:20]  No connection adapters were found for '(u'https://korppi.jyu.fi/calendar/ical/EqY24Na6bQKYaeT',)'
Traceback (most recent call last):
  File "/mnt/DATA/Development/www/matkanaattori/src/application/controller/location.py", line 32, in index
    json = self.location.calculate(lat, lng, userinfo)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/location.py", line 31, in calculate
    nextEvent = calendar.getNextEvent(*userinfo['calendar_url'])
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 26, in getNextEvent
    cachedEvents = getCalendarEvents(url)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 16, in getCalendarEvents
    calendar = getCalendar(url)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 10, in getCalendar
    request = get(url)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 553, in send
    adapter = self.get_adapter(url=request.url)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 598, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
InvalidSchema: No connection adapters were found for '(u'https://korppi.jyu.fi/calendar/ical/EqY24Na6bQKYaeT',)'
[20/Dec/2015:16:12:20] HTTP 
Request Headers:
  COOKIE: session_id=1df681c2ef409ff566ab600859d4a7c751ce4906
  HOST: localhost:8080
  CONNECTION: keep-alive
  Remote-Addr: 127.0.0.1
  ACCEPT: */*
  USER-AGENT: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:43.0) Gecko/20100101 Firefox/43.0
  X-REQUESTED-WITH: XMLHttpRequest
  ACCEPT-LANGUAGE: en-US,en;q=0.5
  Content-Type: text/xml; charset=utf-8
  REFERER: http://localhost:8080/
  ACCEPT-ENCODING: gzip, deflate
[20/Dec/2015:16:12:20] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/jsontools.py", line 63, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/controller/location.py", line 36, in index
    raise Exception("Location calculation failed.")
Exception: Location calculation failed.
[20/Dec/2015:16:14:00]  No connection adapters were found for '(u'https://korppi.jyu.fi/calendar/ical/EqY24Na6bQKYaeT',)'
Traceback (most recent call last):
  File "/mnt/DATA/Development/www/matkanaattori/src/application/controller/location.py", line 32, in index
    json = self.location.calculate(lat, lng, userinfo)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/location.py", line 31, in calculate
    nextEvent = calendar.getNextEvent(*userinfo['calendar_url'])
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 26, in getNextEvent
    cachedEvents = getCalendarEvents(url)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 16, in getCalendarEvents
    calendar = getCalendar(url)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 10, in getCalendar
    request = get(url)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 553, in send
    adapter = self.get_adapter(url=request.url)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 598, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
InvalidSchema: No connection adapters were found for '(u'https://korppi.jyu.fi/calendar/ical/EqY24Na6bQKYaeT',)'
[20/Dec/2015:16:14:00] HTTP 
Request Headers:
  COOKIE: session_id=1df681c2ef409ff566ab600859d4a7c751ce4906
  HOST: localhost:8080
  CONNECTION: keep-alive
  Remote-Addr: 127.0.0.1
  ACCEPT: */*
  USER-AGENT: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:43.0) Gecko/20100101 Firefox/43.0
  X-REQUESTED-WITH: XMLHttpRequest
  ACCEPT-LANGUAGE: en-US,en;q=0.5
  Content-Type: text/xml; charset=utf-8
  REFERER: http://localhost:8080/
  ACCEPT-ENCODING: gzip, deflate
[20/Dec/2015:16:14:00] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/jsontools.py", line 63, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/controller/location.py", line 36, in index
    raise Exception("Location calculation failed.")
Exception: Location calculation failed.
[20/Dec/2015:16:15:06] ENGINE Keyboard Interrupt: shutting down bus
[20/Dec/2015:16:15:06] ENGINE Bus STOPPING
[20/Dec/2015:16:15:06] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 8080)) shut down
[20/Dec/2015:16:15:06] ENGINE Stopped thread 'Session cleanup'.
[20/Dec/2015:16:15:06] ENGINE Stopped thread '_TimeoutMonitor'.
[20/Dec/2015:16:15:06] ENGINE Bus STOPPED
[20/Dec/2015:16:15:07] ENGINE Bus EXITING
[20/Dec/2015:16:15:07] ENGINE Bus EXITED
[20/Dec/2015:16:15:07] ENGINE Waiting for child threads to terminate...
[20/Dec/2015:16:15:08] ENGINE Listening for SIGHUP.
[20/Dec/2015:16:15:08] ENGINE Listening for SIGTERM.
[20/Dec/2015:16:15:08] ENGINE Listening for SIGUSR1.
[20/Dec/2015:16:15:08] ENGINE Bus STARTING
[20/Dec/2015:16:15:08] ENGINE Started monitor thread '_TimeoutMonitor'.
[20/Dec/2015:16:15:08] ENGINE Serving on http://0.0.0.0:8080
[20/Dec/2015:16:15:08] ENGINE Bus STARTED
[20/Dec/2015:16:15:12] ENGINE Started monitor thread 'Session cleanup'.
[20/Dec/2015:16:15:18]  No connection adapters were found for '(u'https://korppi.jyu.fi/calendar/ical/EqY24Na6bQKYaeT',)'
Traceback (most recent call last):
  File "/mnt/DATA/Development/www/matkanaattori/src/application/controller/location.py", line 32, in index
    json = self.location.calculate(lat, lng, userinfo)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/location.py", line 31, in calculate
    nextEvent = calendar.getNextEvent(*userinfo['calendar_url'])
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 26, in getNextEvent
    cachedEvents = getCalendarEvents(url)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 16, in getCalendarEvents
    calendar = getCalendar(url)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 10, in getCalendar
    request = get(url)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 553, in send
    adapter = self.get_adapter(url=request.url)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 598, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
InvalidSchema: No connection adapters were found for '(u'https://korppi.jyu.fi/calendar/ical/EqY24Na6bQKYaeT',)'
[20/Dec/2015:16:15:34]  No connection adapters were found for '(u'https://korppi.jyu.fi/calendar/ical/EqY24Na6bQKYaeT',)'
Traceback (most recent call last):
  File "/mnt/DATA/Development/www/matkanaattori/src/application/controller/location.py", line 32, in index
    json = self.location.calculate(lat, lng, userinfo)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/location.py", line 31, in calculate
    nextEvent = calendar.getNextEvent(*userinfo['calendar_url'])
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 26, in getNextEvent
    cachedEvents = getCalendarEvents(url)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 16, in getCalendarEvents
    calendar = getCalendar(url)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 10, in getCalendar
    request = get(url)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 553, in send
    adapter = self.get_adapter(url=request.url)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 598, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
InvalidSchema: No connection adapters were found for '(u'https://korppi.jyu.fi/calendar/ical/EqY24Na6bQKYaeT',)'
[20/Dec/2015:16:15:45] ENGINE Keyboard Interrupt: shutting down bus
[20/Dec/2015:16:15:45] ENGINE Bus STOPPING
[20/Dec/2015:16:15:45] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 8080)) shut down
[20/Dec/2015:16:15:45] ENGINE Stopped thread 'Session cleanup'.
[20/Dec/2015:16:15:45] ENGINE Stopped thread '_TimeoutMonitor'.
[20/Dec/2015:16:15:45] ENGINE Bus STOPPED
[20/Dec/2015:16:15:45] ENGINE Bus EXITING
[20/Dec/2015:16:15:45] ENGINE Bus EXITED
[20/Dec/2015:16:15:45] ENGINE Waiting for child threads to terminate...
[20/Dec/2015:16:18:37] ENGINE Listening for SIGHUP.
[20/Dec/2015:16:18:37] ENGINE Listening for SIGTERM.
[20/Dec/2015:16:18:37] ENGINE Listening for SIGUSR1.
[20/Dec/2015:16:18:37] ENGINE Bus STARTING
[20/Dec/2015:16:18:37] ENGINE Started monitor thread '_TimeoutMonitor'.
[20/Dec/2015:16:18:37] ENGINE Serving on http://0.0.0.0:8080
[20/Dec/2015:16:18:37] ENGINE Bus STARTED
[20/Dec/2015:16:18:39] ENGINE Started monitor thread 'Session cleanup'.
[20/Dec/2015:16:18:45]  No connection adapters were found for '(u'https://korppi.jyu.fi/calendar/ical/EqY24Na6bQKYaeT',)'
Traceback (most recent call last):
  File "/mnt/DATA/Development/www/matkanaattori/src/application/controller/location.py", line 32, in index
    json = self.location.calculate(lat, lng, userinfo)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/location.py", line 31, in calculate
    nextEvent = calendar.getNextEvent(*userinfo['calendar_url'])
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 26, in getNextEvent
    cachedEvents = getCalendarEvents(url)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 16, in getCalendarEvents
    calendar = getCalendar(url)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 10, in getCalendar
    request = get(url)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 553, in send
    adapter = self.get_adapter(url=request.url)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 598, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
InvalidSchema: No connection adapters were found for '(u'https://korppi.jyu.fi/calendar/ical/EqY24Na6bQKYaeT',)'
[20/Dec/2015:16:19:07]  No connection adapters were found for '(u'https://korppi.jyu.fi/calendar/ical/EqY24Na6bQKYaeT',)'
Traceback (most recent call last):
  File "/mnt/DATA/Development/www/matkanaattori/src/application/controller/location.py", line 32, in index
    json = self.location.calculate(lat, lng, userinfo)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/location.py", line 31, in calculate
    nextEvent = calendar.getNextEvent(*userinfo['calendar_url'])
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 26, in getNextEvent
    cachedEvents = getCalendarEvents(url)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 16, in getCalendarEvents
    calendar = getCalendar(url)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 10, in getCalendar
    request = get(url)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 553, in send
    adapter = self.get_adapter(url=request.url)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 598, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
InvalidSchema: No connection adapters were found for '(u'https://korppi.jyu.fi/calendar/ical/EqY24Na6bQKYaeT',)'
[20/Dec/2015:16:21:17] ENGINE Keyboard Interrupt: shutting down bus
[20/Dec/2015:16:21:17] ENGINE Bus STOPPING
[20/Dec/2015:16:21:17] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 8080)) shut down
[20/Dec/2015:16:21:17] ENGINE Stopped thread 'Session cleanup'.
[20/Dec/2015:16:21:17] ENGINE Stopped thread '_TimeoutMonitor'.
[20/Dec/2015:16:21:17] ENGINE Bus STOPPED
[20/Dec/2015:16:21:17] ENGINE Bus EXITING
[20/Dec/2015:16:21:17] ENGINE Bus EXITED
[20/Dec/2015:16:21:17] ENGINE Waiting for child threads to terminate...
[20/Dec/2015:16:21:18] ENGINE Listening for SIGHUP.
[20/Dec/2015:16:21:18] ENGINE Listening for SIGTERM.
[20/Dec/2015:16:21:18] ENGINE Listening for SIGUSR1.
[20/Dec/2015:16:21:18] ENGINE Bus STARTING
[20/Dec/2015:16:21:18] ENGINE Started monitor thread '_TimeoutMonitor'.
[20/Dec/2015:16:21:19] ENGINE Serving on http://0.0.0.0:8080
[20/Dec/2015:16:21:19] ENGINE Bus STARTED
[20/Dec/2015:16:21:22] ENGINE Started monitor thread 'Session cleanup'.
[20/Dec/2015:16:21:28]  No connection adapters were found for '(u'https://korppi.jyu.fi/calendar/ical/EqY24Na6bQKYaeT',)'
Traceback (most recent call last):
  File "/mnt/DATA/Development/www/matkanaattori/src/application/controller/location.py", line 32, in index
    json = self.location.calculate(lat, lng, userinfo)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/location.py", line 31, in calculate
    nextEvent = calendar.getNextEvent(*userinfo['calendar_url'])
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 26, in getNextEvent
    cachedEvents = getCalendarEvents(url)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 16, in getCalendarEvents
    calendar = getCalendar(url)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 10, in getCalendar
    request = get(url)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 553, in send
    adapter = self.get_adapter(url=request.url)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 598, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
InvalidSchema: No connection adapters were found for '(u'https://korppi.jyu.fi/calendar/ical/EqY24Na6bQKYaeT',)'
[20/Dec/2015:16:21:59]  No connection adapters were found for '(u'https://korppi.jyu.fi/calendar/ical/EqY24Na6bQKYaeT',)'
Traceback (most recent call last):
  File "/mnt/DATA/Development/www/matkanaattori/src/application/controller/location.py", line 32, in index
    json = self.location.calculate(lat, lng, userinfo)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/location.py", line 31, in calculate
    nextEvent = calendar.getNextEvent(*userinfo['calendar_url'])
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 26, in getNextEvent
    cachedEvents = getCalendarEvents(url)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 16, in getCalendarEvents
    calendar = getCalendar(url)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 10, in getCalendar
    request = get(url)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 553, in send
    adapter = self.get_adapter(url=request.url)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 598, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
InvalidSchema: No connection adapters were found for '(u'https://korppi.jyu.fi/calendar/ical/EqY24Na6bQKYaeT',)'
[20/Dec/2015:16:25:02] ENGINE Keyboard Interrupt: shutting down bus
[20/Dec/2015:16:25:02] ENGINE Bus STOPPING
[20/Dec/2015:16:25:02] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 8080)) shut down
[20/Dec/2015:16:25:02] ENGINE Stopped thread 'Session cleanup'.
[20/Dec/2015:16:25:02] ENGINE Stopped thread '_TimeoutMonitor'.
[20/Dec/2015:16:25:02] ENGINE Bus STOPPED
[20/Dec/2015:16:25:02] ENGINE Bus EXITING
[20/Dec/2015:16:25:02] ENGINE Bus EXITED
[20/Dec/2015:16:25:02] ENGINE Waiting for child threads to terminate...
[20/Dec/2015:16:25:04] ENGINE Listening for SIGHUP.
[20/Dec/2015:16:25:04] ENGINE Listening for SIGTERM.
[20/Dec/2015:16:25:04] ENGINE Listening for SIGUSR1.
[20/Dec/2015:16:25:04] ENGINE Bus STARTING
[20/Dec/2015:16:25:04] ENGINE Started monitor thread '_TimeoutMonitor'.
[20/Dec/2015:16:25:04] ENGINE Serving on http://0.0.0.0:8080
[20/Dec/2015:16:25:04] ENGINE Bus STARTED
[20/Dec/2015:16:25:08] ENGINE Started monitor thread 'Session cleanup'.
[20/Dec/2015:16:25:15]  No connection adapters were found for '(u'https://korppi.jyu.fi/calendar/ical/EqY24Na6bQKYaeT',)'
Traceback (most recent call last):
  File "/mnt/DATA/Development/www/matkanaattori/src/application/controller/location.py", line 32, in index
    return self.location.calculate(lat, lng, userinfo)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/location.py", line 31, in calculate
    nextEvent = calendar.getNextEvent(*userinfo['calendar_url'])
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 26, in getNextEvent
    cachedEvents = getCalendarEvents(url)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 16, in getCalendarEvents
    calendar = getCalendar(url)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 10, in getCalendar
    request = get(url)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 553, in send
    adapter = self.get_adapter(url=request.url)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 598, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
InvalidSchema: No connection adapters were found for '(u'https://korppi.jyu.fi/calendar/ical/EqY24Na6bQKYaeT',)'
[20/Dec/2015:16:27:40]  No connection adapters were found for '(u'https://korppi.jyu.fi/calendar/ical/EqY24Na6bQKYaeT',)'
Traceback (most recent call last):
  File "/mnt/DATA/Development/www/matkanaattori/src/application/controller/location.py", line 32, in index
    return self.location.calculate(lat, lng, userinfo)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/location.py", line 31, in calculate
    nextEvent = calendar.getNextEvent(*userinfo['calendar_url'])
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 26, in getNextEvent
    cachedEvents = getCalendarEvents(url)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 16, in getCalendarEvents
    calendar = getCalendar(url)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 10, in getCalendar
    request = get(url)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 553, in send
    adapter = self.get_adapter(url=request.url)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 598, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
InvalidSchema: No connection adapters were found for '(u'https://korppi.jyu.fi/calendar/ical/EqY24Na6bQKYaeT',)'
[20/Dec/2015:16:28:02]  No connection adapters were found for '(u'https://korppi.jyu.fi/calendar/ical/EqY24Na6bQKYaeT',)'
Traceback (most recent call last):
  File "/mnt/DATA/Development/www/matkanaattori/src/application/controller/location.py", line 32, in index
    return self.location.calculate(lat, lng, userinfo)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/location.py", line 31, in calculate
    nextEvent = calendar.getNextEvent(*userinfo['calendar_url'])
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 26, in getNextEvent
    cachedEvents = getCalendarEvents(url)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 16, in getCalendarEvents
    calendar = getCalendar(url)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 10, in getCalendar
    request = get(url)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 553, in send
    adapter = self.get_adapter(url=request.url)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 598, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
InvalidSchema: No connection adapters were found for '(u'https://korppi.jyu.fi/calendar/ical/EqY24Na6bQKYaeT',)'
[20/Dec/2015:16:31:46] ENGINE Keyboard Interrupt: shutting down bus
[20/Dec/2015:16:31:46] ENGINE Bus STOPPING
[20/Dec/2015:16:31:46] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 8080)) shut down
[20/Dec/2015:16:31:46] ENGINE Stopped thread '_TimeoutMonitor'.
[20/Dec/2015:16:31:46] ENGINE Stopped thread 'Session cleanup'.
[20/Dec/2015:16:31:46] ENGINE Bus STOPPED
[20/Dec/2015:16:31:46] ENGINE Bus EXITING
[20/Dec/2015:16:31:46] ENGINE Bus EXITED
[20/Dec/2015:16:31:46] ENGINE Waiting for child threads to terminate...
[20/Dec/2015:16:33:17] ENGINE Listening for SIGHUP.
[20/Dec/2015:16:33:17] ENGINE Listening for SIGTERM.
[20/Dec/2015:16:33:17] ENGINE Listening for SIGUSR1.
[20/Dec/2015:16:33:17] ENGINE Bus STARTING
[20/Dec/2015:16:33:17] ENGINE Started monitor thread '_TimeoutMonitor'.
[20/Dec/2015:16:33:17] ENGINE Serving on http://0.0.0.0:8080
[20/Dec/2015:16:33:17] ENGINE Bus STARTED
[20/Dec/2015:16:33:21] ENGINE Started monitor thread 'Session cleanup'.
[20/Dec/2015:16:33:29]  No connection adapters were found for '(u'https://korppi.jyu.fi/calendar/ical/EqY24Na6bQKYaeT',)'
Traceback (most recent call last):
  File "/mnt/DATA/Development/www/matkanaattori/src/application/controller/location.py", line 23, in index
    return self.location.calculate(lat, lng, userinfo)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/location.py", line 29, in calculate
    nextEvent = calendar.getNextEvent(*userinfo['calendar_url'])
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 26, in getNextEvent
    cachedEvents = getCalendarEvents(url)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 16, in getCalendarEvents
    calendar = getCalendar(url)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 10, in getCalendar
    request = get(url)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 553, in send
    adapter = self.get_adapter(url=request.url)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 598, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
InvalidSchema: No connection adapters were found for '(u'https://korppi.jyu.fi/calendar/ical/EqY24Na6bQKYaeT',)'
[20/Dec/2015:16:35:14] ENGINE Keyboard Interrupt: shutting down bus
[20/Dec/2015:16:35:14] ENGINE Bus STOPPING
[20/Dec/2015:16:35:14] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 8080)) shut down
[20/Dec/2015:16:35:14] ENGINE Stopped thread 'Session cleanup'.
[20/Dec/2015:16:35:14] ENGINE Stopped thread '_TimeoutMonitor'.
[20/Dec/2015:16:35:14] ENGINE Bus STOPPED
[20/Dec/2015:16:35:14] ENGINE Bus EXITING
[20/Dec/2015:16:35:14] ENGINE Bus EXITED
[20/Dec/2015:16:35:14] ENGINE Waiting for child threads to terminate...
[20/Dec/2015:16:35:16] ENGINE Listening for SIGHUP.
[20/Dec/2015:16:35:16] ENGINE Listening for SIGTERM.
[20/Dec/2015:16:35:16] ENGINE Listening for SIGUSR1.
[20/Dec/2015:16:35:16] ENGINE Bus STARTING
[20/Dec/2015:16:35:16] ENGINE Started monitor thread '_TimeoutMonitor'.
[20/Dec/2015:16:35:17] ENGINE Serving on http://0.0.0.0:8080
[20/Dec/2015:16:35:17] ENGINE Bus STARTED
[20/Dec/2015:16:37:10] ENGINE Started monitor thread 'Session cleanup'.
[20/Dec/2015:16:38:01] ENGINE Keyboard Interrupt: shutting down bus
[20/Dec/2015:16:38:01] ENGINE Bus STOPPING
[20/Dec/2015:16:38:01] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 8080)) shut down
[20/Dec/2015:16:38:01] ENGINE Stopped thread 'Session cleanup'.
[20/Dec/2015:16:38:01] ENGINE Stopped thread '_TimeoutMonitor'.
[20/Dec/2015:16:38:01] ENGINE Bus STOPPED
[20/Dec/2015:16:38:01] ENGINE Bus EXITING
[20/Dec/2015:16:38:01] ENGINE Bus EXITED
[20/Dec/2015:16:38:01] ENGINE Waiting for child threads to terminate...
[20/Dec/2015:16:38:03] ENGINE Listening for SIGHUP.
[20/Dec/2015:16:38:03] ENGINE Listening for SIGTERM.
[20/Dec/2015:16:38:03] ENGINE Listening for SIGUSR1.
[20/Dec/2015:16:38:03] ENGINE Bus STARTING
[20/Dec/2015:16:38:03] ENGINE Started monitor thread '_TimeoutMonitor'.
[20/Dec/2015:16:38:03] ENGINE Serving on http://0.0.0.0:8080
[20/Dec/2015:16:38:03] ENGINE Bus STARTED
[20/Dec/2015:16:38:47] ENGINE Started monitor thread 'Session cleanup'.
[20/Dec/2015:16:40:01] ENGINE Keyboard Interrupt: shutting down bus
[20/Dec/2015:16:40:01] ENGINE Bus STOPPING
[20/Dec/2015:16:40:01] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 8080)) shut down
[20/Dec/2015:16:40:01] ENGINE Stopped thread 'Session cleanup'.
[20/Dec/2015:16:40:01] ENGINE Stopped thread '_TimeoutMonitor'.
[20/Dec/2015:16:40:01] ENGINE Bus STOPPED
[20/Dec/2015:16:40:01] ENGINE Bus EXITING
[20/Dec/2015:16:40:01] ENGINE Bus EXITED
[20/Dec/2015:16:40:01] ENGINE Waiting for child threads to terminate...
[20/Dec/2015:16:40:10] ENGINE Listening for SIGHUP.
[20/Dec/2015:16:40:10] ENGINE Listening for SIGTERM.
[20/Dec/2015:16:40:10] ENGINE Listening for SIGUSR1.
[20/Dec/2015:16:40:10] ENGINE Bus STARTING
[20/Dec/2015:16:40:10] ENGINE Started monitor thread '_TimeoutMonitor'.
[20/Dec/2015:16:40:10] ENGINE Serving on http://0.0.0.0:8080
[20/Dec/2015:16:40:10] ENGINE Bus STARTED
[20/Dec/2015:16:40:16] ENGINE Started monitor thread 'Session cleanup'.
[20/Dec/2015:16:40:52]  No connection adapters were found for '(u'https://korppi.jyu.fi/calendar/ical/EqY24Na6bQKYaeT',)'
Traceback (most recent call last):
  File "/mnt/DATA/Development/www/matkanaattori/src/application/controller/location.py", line 23, in index
    return self.location.calculate(lat, lng, userinfo)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/location.py", line 29, in calculate
    nextEvent = calendar.getNextEvent(*userinfo['calendar_url'])
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 28, in getNextEvent
    cachedEvents = getCalendarEvents(url)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 17, in getCalendarEvents
    calendar = getCalendar(url)
  File "/mnt/DATA/Development/www/matkanaattori/src/application/model/calendar.py", line 11, in getCalendar
    request = get(url)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 553, in send
    adapter = self.get_adapter(url=request.url)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 598, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
InvalidSchema: No connection adapters were found for '(u'https://korppi.jyu.fi/calendar/ical/EqY24Na6bQKYaeT',)'
[20/Dec/2015:16:41:50] ENGINE Keyboard Interrupt: shutting down bus
[20/Dec/2015:16:41:50] ENGINE Bus STOPPING
[20/Dec/2015:16:41:50] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 8080)) shut down
[20/Dec/2015:16:41:50] ENGINE Stopped thread '_TimeoutMonitor'.
[20/Dec/2015:16:41:50] ENGINE Stopped thread 'Session cleanup'.
[20/Dec/2015:16:41:50] ENGINE Bus STOPPED
[20/Dec/2015:16:41:50] ENGINE Bus EXITING
[20/Dec/2015:16:41:50] ENGINE Bus EXITED
[20/Dec/2015:16:41:50] ENGINE Waiting for child threads to terminate...
